### ISSUE TITLE
issues to install docker-engine-1.11.2-1.el7

### ISSUE THREAD

**Issue by Pitsyjulio** [docker/leadership#4]
Hello.

recently we tried to install docker in our Linux machine using yum and we are facing the following issue .

--> Finished Dependency Resolution
Error: Package: docker-engine-1.11.2-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libdevmapper.so.1.02(DM_1_02_97)(64bit)
Error: Package: docker-engine-1.11.2-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libsystemd.so.0()(64bit)
Error: Package: docker-engine-1.11.2-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libltdl.so.7()(64bit)
Error: Package: docker-engine-1.11.2-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

kernel version
3.10.0-123.13.2.el7.x86_64
OS
Red Hat Enterprise Linux Server release 7.1 
 python --version
Python 2.7.5

could you please help us?

**Comment by abronan** [comment]
Hi @Pitsyjulio, this is a question for [docker/docker](https://github.com/docker/docker). Feel free to open an issue there if this is still a problem.

Thanks.
