### ISSUE TITLE
Is this a bug? When watch channel is closed, follower loop need break.

### ISSUE THREAD

**Issue by zhijiay** [docker/leadership#8]
https://github.com/docker/leadership/blob/0a913e2d71a12fd14a028452435cb71ac8d82cb6/follower.go#L62

**Comment by zhixinwen** [comment]
I think this should be a bug, and it is hurting us in some cases... For example when session expires and watches are invalidated, followers do not know

**Comment by zhixinwen** [comment]
If channel is closed, the program would break out of for loop directly
